apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-expense
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-expense
  template:
    metadata:
      labels:
        app: api-expense
    spec:
      containers:
      - name: api-expense
        image: expense-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
